### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by costales** [comment]
Translations in Launchpad please. Thanks.

**Comment by Vistaus** [comment]
But you migrated to GitHub...

But if you insist, how do I upload po files to Launchpad?

**Comment by costales** [comment]
Not the translations

**Comment by Vistaus** [comment]
But how do I upload po files to Launchpad?

**Comment by costales** [comment]
Hi, just login and in your language you can upload it. Best regards and
thanks in advance

**Comment by Vistaus** [comment]
Thanks for your answer, but I only see "Download translation" on the Launchpad translation page. No upload button. I am logged in.

**Comment by costales** [comment]
For example, in https://translations.launchpad.net/unav you have a link for
upload: ''Launchpad currently recommends translating uNav trunk series
<https://translations.launchpad.net/unav/trunk>. You can also download
<https://translations.launchpad.net/unav/trunk/+export> or upload
<https://translations.launchpad.net/unav/trunk/+translations-upload>
translations
for trunk.'
https://translations.launchpad.net/unav/trunk/+translations-upload

**Comment by Vistaus** [comment]
Hmm, the upload page says "The information on this page is private." :/

**Comment by costales** [comment]
Are you logged? I think to remember you can upload .po files

**Comment by Vistaus** [comment]
Yes, I am, but I cannot upload po files.

**Pull request closed without merging**
